package com.example.model;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.*;

import javax.validation.constraints.NotBlank;

/**
 * Represents a User object used in the Reqres API.
 * Uses Lombok annotations for reducing boilerplate code.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    // User fields with validation
    @NotBlank(message = "Name is mandatory")
    private String name;

    @NotBlank(message = "Job is mandatory")
    private String job;

    private String id;          // Generated by the API during creation
    private String createdAt;   // Generated timestamp
    private String updatedAt;
    private String email;
    private String first_name;
    private String last_name;
    private String avatar;


    /**
     * Converts the User object to a JSON string.
     * @return JSON representation of the User object.
     */
    public String toJson() {
        try {
            return new ObjectMapper().writeValueAsString(this);
        } catch (JsonProcessingException e) {
            throw new RuntimeException("Error serializing User to JSON", e);
        }
    }
}
